#:schema node_modules/wrangler/config-schema.json
name = "framer-genie"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { binding = "keyValueStore", id = "6f48c3823c1b4a6e8942c9b5afc37f1a" },
]

[vars]
PLUGIN_PARENT_DOMAIN = "plugins.framercdn.com"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



